### ISSUE TITLE
libzmq doesn't build on freebsd 10.2

### ISSUE THREAD

**Issue by crypto750** [zeromq/czmq#1112]
CXXLD    tools/curve_keygen
src/.libs/libzmq.so: undefined reference to `crypto_secretbox_open'
src/.libs/libzmq.so: undefined reference to`crypto_box_beforenm'
src/.libs/libzmq.so: undefined reference to `crypto_secretbox'
src/.libs/libzmq.so: undefined reference to`crypto_box'
src/.libs/libzmq.so: undefined reference to `crypto_box_keypair'
src/.libs/libzmq.so: undefined reference to`sodium_init'
src/.libs/libzmq.so: undefined reference to `crypto_box_open'
src/.libs/libzmq.so: undefined reference to`randombytes_close'
src/.libs/libzmq.so: undefined reference to `crypto_box_open_afternm'
src/.libs/libzmq.so: undefined reference to`randombytes'
src/.libs/libzmq.so: undefined reference to `crypto_box_afternm'
c++: error: linker command failed with exit code 1 (use -v to see 
invocation)
**\* Error code 1

**Comment by Asmod4n** [comment]
Looks like libsodium isn't installed or cannot be found

**Comment by crypto750** [comment]
hm, libsodium is installed, and I did 
setenv sodium_CFLAGS "-I/usr/local/include"
setenv sodium_LIBS "-L/usr/local/lib"
to make sure it's found.
Should I use any additional flags with --configure?

**Comment by crypto750** [comment]
ldconfig -r | grep sodium

528:-lsodium.13 => /usr/local/lib/libsodium.so.13

everything is in place.

/usr/local/include/sodium.h
/usr/local/include/sodium

**Comment by crypto750** [comment]
I tried building from freebsd ports... same error. libsodium is successfully built as a dependency, but libzmq miserably fails.

**Comment by Asmod4n** [comment]
whats the output of ldd on the libzmq and czmq shared objects?

**Comment by crypto750** [comment]
Well, I solved this problem copying libsodium.pc /usr/local/libdata/pkgconfig/   this sets the flag -lsodium for compiling libzmq.
After installing libzmq, copy src/libzmq.pc /usr/local/libdata/pkgconfig/    to set the flag -lzmq
After installing czmq, copy src/libczmq.pc /usr/local/libdata/pkgconfig/    to set the flag -lczmq

**Comment by sappo** [comment]
On linux `sudo make install` does exactly this. The question is why does it not work on FreeBSD?

**Comment by bluca** [comment]
Closing for housekeeping since it was solved by using pkgconfig
