### ISSUE TITLE
zproxy.c broken

### ISSUE THREAD

**Issue by claws** [zeromq/czmq#344]
CZMQ's Travis builds and my zeromq-buildbot builds are breaking with the same errors which I think were introduced by #343:

<pre><code>
zproxy.c: In function ‘zproxy_test’:
zproxy.c:485:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:486:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:510:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:511:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:530:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:557:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:564:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:565:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:571:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:582:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:592:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:600:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:611:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:612:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:621:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:657:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:672:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:681:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:695:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:697:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:698:1: error: embedding a directive within macro arguments is not portable [-Werror]
zproxy.c:699:0: error: unterminated argument list invoking macro "assert"
zproxy.c:409:5: error: ‘assert’ undeclared (first use in this function)
zproxy.c:409:5: note: each undeclared identifier is reported only once for each function it appears in
zproxy.c:409:5: error: expected ‘;’ at end of input
zproxy.c:409:5: error: expected declaration or statement at end of input
zproxy.c:396:11: error: unused variable ‘control_addr’ [-Werror=unused-variable]
zproxy.c:395:11: error: unused variable ‘capture_addr’ [-Werror=unused-variable]
zproxy.c:394:11: error: unused variable ‘backend_addr’ [-Werror=unused-variable]
zproxy.c:393:11: error: unused variable ‘frontend_addr’ [-Werror=unused-variable]
zproxy.c: At top level:
zproxy.c:114:5: error: ‘s_agent_task’ used but never defined [-Werror]
zproxy.c:382:1: error: ‘s_zproxy_test_run’ declared ‘static’ but never defined [-Werror=unused-function]
zproxy.c: In function ‘zproxy_test’:
zproxy.c:409:5: error: control reaches end of non-void function [-Werror=return-type]
cc1: all warnings being treated as errors
make[1]: *** [zproxy.lo] Error 1
make[1]: Leaving directory `/home/travis/build/zeromq/czmq/src'
make: *** [check-recursive] Error 1
</code></pre>
